### PR TITLE
clean up .pot file

### PR DESCRIPTION
**Pull request by senlin**
Hi Justin,

Your .pot file seems to be copied from a Dutch translation file from your hybrid theme.

I cleaned it up, so now it can be used to make .po and .mo files from.

Piet

### CODE REVIEW

**Comment by senlin** [comment]
sorry for the double file, the 2nd is what you should have a look at as that is a full redo of the file

**Comment by justintadlock** [comment]
That's weird. Check out this changeset:
https://github.com/justintadlock/whistles/commit/b4493053474155eff3e59ef258336692bf691bd0

I made that change on the 0.1 branch (not the stable master branch).

**Comment by senlin** [comment]
Perhaps you didn't merge it into the master then?

**Comment by senlin** [comment]
The [whistles.pot](https://github.com/justintadlock/whistles/blob/0.1/languages/whistles.pot) file of the 0.1 branch also contains all the fuzzy strings, which can be removed in my opinion. (line 229 onwards)

**Comment by justintadlock** [comment]
Hmm...For some reason, these are not showing up in Poedit.

> Perhaps you didn't merge it into the master then?

Master is for stable releases, not development.

**Comment by justintadlock** [comment]
This should do it:
https://github.com/justintadlock/whistles/commit/5faec978652a1c7423a3a1f7d7f7bc9da2e5b847

**Comment by senlin** [comment]
yup, that's it

**Pull request closed without merging**
